### ISSUE TITLE
ggalt development version does not support some projections

### ISSUE THREAD

**Issue by michaeljaywalsh** [JGCRI/gcammaptools#19]
The current development version of ggalt did not support eck3, robinson and witntri projections resulting in the following error when using plot_GCAM:

`Error in zero_range(from) : x must be length 1 or 2`

The issue was fixed by installing and older commit (12/30/16):
`devtools::install_github('hrbrmstr/ggalt',ref="017b4824f3")`

**Comment by pralitp** [comment]
Thanks!  I was running into this same issue just the other day and bailed because I didn't know where this was coming from.  Sure enough this fixed it for me too.

We can update the documentation although maybe there is a better longterm solution?  I know @rplzzz had (different?) issues with ggalt in the past.

**Comment by rplzzz** [comment]
The issue I had was related to changes in ggplot, but I submitted a PR to ggalt to fix it.  I'll see if I can figure out what changed in ggalt and either submit another fix (if I can figure it out) or post an issue there (if not).

@michaeljaywalsh did you observe that the problem was _only_ in those three projections and not in others, or were those just the ones that you tested?

**Comment by michaeljaywalsh** [comment]
It worked with ortho, but I think that was all I tested

**Comment by rplzzz** [comment]
The orthographic projections don't use ggalt, so that seems consistent.

**Comment by rplzzz** [comment]
FYI, I should have a fix for this shortly.  The new updates should be consistent with ggplot2 v 2.2.1, and I have a fork of ggalt that works as well.
