### ISSUE TITLE
gcam32_colors is not exported

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcammaptools#21]
I see gcam14_colors is exported, but not 32 colors. Seems like it should be, but I'm just starting to look at the package, so might be my error...

**Comment by rplzzz** [comment]
The `gcam32_colors` in this package is bogus.  I've got a better one in another package that I can graft in here for the time being.  In the long run, stuff like this should go into a separate graphics utilities package of its own, since it isn't specific to any one type of plot, but I haven't gotten around to organizing that yet.

**Comment by rplzzz** [comment]
`gcam32_colors` is no longer bogus.
